const CHART_CONFIG = Object.freeze({ temperatureThresholds: Object.freeze({ normal: 30, warning: 38, unsafe: 45 }), telemetryWindow: 24, staleAfterMs: 5000 });
const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)]; let selectedId = null; let cache = { assets: null, priorities: null, audit: null, telemetry: new Map() };
const thresholdLabels = $$('.chart-labels text'); if (thresholdLabels.length >= 3) Object.values(CHART_CONFIG.temperatureThresholds).forEach((value, i) => { thresholdLabels[i].textContent = `${value}°C`; });
$$('[data-route]').forEach((link) => link.addEventListener('click', (e) => { const route = window.RakshakRoutes?.[link.dataset.route]; if (route?.path) { e.preventDefault(); window.location.href = route.path; } }));
const levelColor = { LOW:'#22c55e', MEDIUM:'#f2a93b', HIGH:'#ef4444', CRITICAL:'#ef4444' };
$$('[data-pending]').forEach((link) => link.addEventListener('click', (e) => { const route = Object.values(window.RakshakRoutes || {}).find((item) => item.label === link.dataset.pending); if (route?.path) { e.preventDefault(); window.location.href = route.path; return; } e.preventDefault(); const status = $('.nav-status'); status.textContent = `${link.dataset.pending} route pending.`; }));
async function selectAsset(assetId){selectedId=assetId;const asset=cache.assets&&((Array.isArray(cache.assets)?cache.assets:cache.assets.assets)||[]).find((item)=>item.id===assetId);$('[data-selected-asset]').textContent=assetId||'AWAITING SELECTION';let link=$('[data-open-safety-case]');if(!link){link=document.createElement('a');link.dataset.openSafetyCase='';link.className='selected-case-link';link.textContent='OPEN SAFETY CASE →';$('.trajectory .panel-head').append(link)}link.href=`asset-safety-case.html?asset=${encodeURIComponent(assetId)}`;try{const telemetry=await window.RakshakAPI.loadTelemetry(assetId,CHART_CONFIG.telemetryWindow);renderChart(telemetry);}catch(e){if(!cache.telemetry.has(assetId))$('[data-telemetry-state]').textContent='TELEMETRY UNAVAILABLE';}}
function openAssetSafetyCase(assetId){const route=window.RakshakRoutes?.safetyCase;const status=$('.nav-status');if(route?.path)window.location.href=`${route.path}?asset=${encodeURIComponent(assetId)}`;else if(status)status.textContent=`${route?.label||'Asset Safety Case'} route pending.`;}
function gauge(score) { const value = Number(score); return Number.isFinite(value) ? Math.max(0, Math.min(100, value)) : null; }
function gaugeSvg(score, level) { const v = gauge(score); const angle = v === null ? -135 : -135 + v * 2.7; return `<svg class="mini-gauge" viewBox="0 0 120 100" aria-label="Risk index ${v ?? 'awaiting'}"><path class="mini-track" d="M15 82 A45 45 0 1 1 105 82"/><line class="mini-needle" style="transform:rotate(${angle}deg);stroke:${levelColor[level] || '#8a93a1'}" x1="60" y1="82" x2="60" y2="38"/><circle cx="60" cy="82" r="4"/></svg>`; }
function sparklineSvg(assetId){const points=normalizedTelemetry(cache.telemetry.get(assetId)||[]);if(points.length<2)return '<span class="instrument-trend awaiting">TREND AWAITING TELEMETRY</span>';const min=20,max=50,coords=points.map((p,i)=>`${(i/(points.length-1))*100},${30-((Math.max(min,Math.min(max,p.temperature))-min)/(max-min))*25}`).join(' ');return `<svg class="instrument-sparkline" viewBox="0 0 100 30" preserveAspectRatio="none" aria-label="Live temperature trend"><polyline points="${coords}"/></svg>`;}
function renderAssets(items) { const el = $('[data-assets]'); if (!el) return; if (!items?.length) { el.innerHTML='<div class="loading-block">ASSET DATA UNAVAILABLE</div>'; return; } el.innerHTML=''; items.forEach((asset) => { const risk=asset.risk||{}; const card=document.createElement('a'); card.className='asset-instrument'; card.href='#'; card.dataset.assetId=asset.id||''; card.innerHTML=`<div class="instrument-top"><span>${asset.id??'—'}</span><b style="color:${levelColor[risk.level]||'#8a93a1'}">${risk.level??'—'}</b></div>${gaugeSvg(risk.score,risk.level)}${sparklineSvg(asset.id)}<div class="instrument-score">${risk.score??'—'}<small>/ 100</small></div><strong>${asset.name??'—'}</strong><span class="instrument-location">${asset.location??'—'}</span><div class="instrument-priority"><span>PRIORITY</span><b>${risk.priority??asset.priority??'—'}</b></div>`; card.addEventListener('click',(e)=>{e.preventDefault();selectAsset(asset.id);}); el.append(card); }); }
function renderPriorities(items) { const el=$('[data-priority-table]'); if(!el)return; if(!items?.length){el.innerHTML='<div class="loading-block">PRIORITY DATA UNAVAILABLE</div>';return;} el.innerHTML='<div class="table-row table-head"><span>RANK</span><span>ASSET</span><span>RISK</span><span>LEVEL</span><span>PRIORITY</span><span>TREND</span></div>'; items.forEach((item)=>{const row=document.createElement('a');row.className='table-row';row.href='#';row.innerHTML=`<strong>#${item.rank??'—'}</strong><span>${item.name??'—'}<small>${item.asset_id??'—'}</small></span><b>${item.risk??'—'}</b><em style="color:${levelColor[item.level]||'#8a93a1'}">${item.level??'—'}</em><b>${item.priority??'—'}</b><small>${item.trend??'—'}</small>`;row.addEventListener('click',(e)=>{e.preventDefault();selectAsset(item.asset_id);});el.append(row);}); }
function renderAlerts(items) { const el=$('[data-alerts]'); if(!el)return; if(!items?.length){el.innerHTML='<div class="no-alerts">NO ACTIVE ALERTS — PLANT NOMINAL.</div>';return;} el.innerHTML=''; [...items].reverse().slice(0,6).forEach((event)=>{const row=document.createElement('div');row.className='alert-row';row.innerHTML=`<time>${event.timestamp??event.created_at??'—'}</time><strong>${event.asset_id??'—'}</strong><span>${event.event_type??'—'}</span><small>${typeof event.payload==='string'?event.payload:event.payload?JSON.stringify(event.payload):'—'}</small>`;el.append(row);}); }
function normalizedTelemetry(data){return (Array.isArray(data)?data:[]).map((p)=>({timestamp:p.timestamp??p.created_at??p.time,temperature:p.temperature_c??p.temperature,id:p.id??p.timestamp??p.created_at})).filter((p)=>p.timestamp&&p.temperature!==null&&p.temperature!==undefined&&Number.isFinite(Number(p.temperature))).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)).slice(-CHART_CONFIG.telemetryWindow);}
function renderChart(data){const incoming=normalizedTelemetry(data),previous=cache.telemetry.get(selectedId)||[],merged=new Map(normalizedTelemetry(previous).map((p)=>[String(p.id),p]));incoming.forEach((p)=>merged.set(String(p.id),p));const points=[...merged.values()].sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp)).slice(-CHART_CONFIG.telemetryWindow);cache.telemetry.set(selectedId,points);const line=$('[data-trajectory-line]'),group=$('[data-chart-points]');if(!line||!group)return;const empty=$('[data-chart-empty]');if(!points.length){line.setAttribute('d','');if(empty)empty.hidden=false;return;}if(empty)empty.hidden=true;const min=20,max=50;const coords=points.map((p,i)=>[50+(i/(Math.max(points.length-1,1)))*720,245-((Math.max(min,Math.min(max,Number(p.temperature))-min)/(max-min))*210)]);line.setAttribute('d',coords.map((p,i)=>`${i?'L':'M'} ${p[0]} ${p[1]}`).join(' '));const live=new Map([...group.querySelectorAll('circle')].map((node)=>[node.dataset.telemetryId,node]));const ids=new Set();coords.forEach((p,i)=>{const id=String(points[i].id);ids.add(id);let node=live.get(id);if(!node){node=document.createElementNS('http://www.w3.org/2000/svg','circle');node.setAttribute('tabindex','0');node.setAttribute('focusable','true');node.dataset.telemetryId=id;node.setAttribute('r','3');const title=document.createElementNS('http://www.w3.org/2000/svg','title');node.append(title);group.append(node);}node.setAttribute('cx',p[0]);node.setAttribute('cy',p[1]);node.querySelector('title').textContent=`${new Date(points[i].timestamp).toLocaleString()} / ${points[i].temperature}°C`;});live.forEach((node,id)=>{if(!ids.has(id))node.remove();});$('[data-chart-start]').textContent=new Date(points[0].timestamp).toLocaleTimeString([], {hour12:false});$('[data-chart-end]').textContent=new Date(points.at(-1).timestamp).toLocaleTimeString([], {hour12:false});const last=new Date(points.at(-1).timestamp);$('[data-telemetry-state]').textContent=Date.now()-last.getTime()>CHART_CONFIG.staleAfterMs?'STALE DATA':'TELEMETRY LINKED';}
function summarize(items){if(!items?.length)return 'AWAITING LIVE DATA'; if(items.some((a)=>(a.risk?.level||a.level)==='CRITICAL'))return 'CRITICAL'; if(items.some((a)=>(a.risk?.level||a.level)==='HIGH'))return 'HIGH RISK'; if(items.some((a)=>(a.risk?.level||a.level)==='MEDIUM'))return 'ATTENTION'; return 'NOMINAL';}
async function refresh(){try{const assets=await window.RakshakAPI.loadAssets(); cache.assets=assets; const list=Array.isArray(assets)?assets:assets.assets; renderAssets(list); $('[data-plant-status]').textContent=summarize(list); $('[data-plant-count]').textContent=`${list?.length??0} MONITORED ASSETS`; $('[data-assets-state]').textContent='ASSET DATA LINKED'; if(!selectedId&&list?.length)selectedId=list[0].id; if(selectedId){const telemetry=await window.RakshakAPI.loadTelemetry(selectedId);cache.telemetry.set(selectedId,telemetry);renderChart(telemetry);$('[data-selected-asset]').textContent=selectedId;$('[data-telemetry-state]').textContent='TELEMETRY LINKED';}}catch(e){if(!cache.assets)$('[data-assets-state]').textContent='ASSET DATA UNAVAILABLE';}try{const priorities=await window.RakshakAPI.loadPriorities();cache.priorities=priorities;renderPriorities(Array.isArray(priorities)?priorities:priorities.priorities);$('[data-priority-state]').textContent='PRIORITY DATA LINKED';}catch(e){}try{const audit=await window.RakshakAPI.loadAudit();cache.audit=audit;renderAlerts(Array.isArray(audit)?audit:audit.events);$('[data-audit-state]').textContent='AUDIT DATA LINKED';}catch(e){}}
refresh(); window.setInterval(refresh,900);
